# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('Question', models.TextField()),
                ('Choice1', models.CharField(max_length=200)),
                ('Choice2', models.CharField(max_length=200)),
                ('Choice3', models.CharField(max_length=200)),
                ('Choice4', models.CharField(max_length=200)),
                ('Choice5', models.CharField(max_length=200)),
                ('Correct_Ans', models.CharField(max_length=200)),
            ],
        ),
    ]
