# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170201_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_ans',
        ),
    ]
