# Generated by Django 2.0.3 on 2018-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mark',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
