# Generated by Django 2.0.3 on 2018-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mark',
            new_name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
