# Generated by Django 2.0.3 on 2018-03-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_question_choice5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
